name: Pull Request Test Routine

on: pull_request

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: |
            - recursive: true
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
